name: Compile Project

# Trigger the workflow every time you push to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code onto the runner
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Run the make command
    - name: Run Makefile
      run: |
        make
